// CONNECT TO DB
export const CONNECTING_TO_DB = 'APP/CONNECTING_TO_DB';
export const CONNECTED_TO_DB = 'APP/CONNECTED_TO_DB';
export const FAILED_CONNECTED_TO_DB = 'APP/FAILED_CONNECTED_TO_DB';

// LOGIN
export const LOGGING_IN = 'APP/LOGGING_IN';
export const LOGGED_IN = 'APP/LOGGED_IN';
export const FAILED_LOGGED_IN = 'APP/FAILED_LOGGED_IN';
export const NO_SUCH_USER = 'APP/NO_SUCH_USER';

// LOCATIONS
export const GETTING_LOCATIONS = 'APP/GETTING_LOCATIONS';
export const GOT_LOCATIONS = 'APP/GOT_LOCATIONS';
export const FAILED_GETTING_LOCATIONS = 'APP/FAILED_GETTING_LOCATIONS';
